### ISSUE TITLE
Unimplemented traits/skills

### ISSUE THREAD

**Issue by marcustyphoon** [discretize/discretize-gear-optimizer#903]
- Power Block
- Replenishing Despair
- Untamed ambush skill life steal
- Distracting Daggers

could be added but serves no purpose:

```yaml
    - id: pyromancers-puissance
      text: Pyromancer's Puissance
      subText: ≥10 might
      amountData:
        label: '/10s'
        default: 0
        defaultInput: ???
        quantityEntered: 10
      modifiers:
        attributes:
          Power Coefficient: 1381 # 690.5 * 2
          Burning Coefficient: 7
      gw2id: 294
      defaultEnabled: true
      temporaryBuff: true
```
